# Generated by Django 3.2.25 on 2024-10-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
