# Generated by Django 3.2.25 on 2024-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_remove_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothings', 'Clothings'), ('Electronics', 'Electronics'), ('Home', 'Home')], max_length=30, null=True),
        ),
    ]
